service: fapi

provider:
  name: aws
  runtime: python3.11
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:Query
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:*:table/dev-fapi-ddb

functions:
  ingestPlayersData:
    handler: ingester.handler

resources:
  Resources:
    FapiTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: dev-fapi-ddb
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
